### ISSUE TITLE
Calculation of RPKM

### ISSUE THREAD

**Issue by jerceyli** [wwood/CoverM#11]
Hello,

I am trying to calculate RPKM value from the result of CoverM. RPKM = (mapNumReads * 10^9) / ( genomeLength * totalNumReads ). RPKM calculation don‘t refer to the length of each read, while CoverM does. It is not so smooth to eliminate this part from the results no matter which method, because my datas come from different sequencing platforms and they have inconsistent length of reads. So, I wonder how to determine CoverM method and how to use the result to further calculate RPKM value.

Best ragards,
Jercey

**Comment by wwood** [comment]
Hi,

Thanks for your interest.

Unfortunately there's no `-m rpkm` which would be the ideal answer to your question, at least yet - I'll leave this issue open until there is.

But, it is possible if you find the total number of mapped reads to all genomes (let's all this `total_reads_mapped_to_all_genomes`), and then use the `-m reads_per_base` so that the number of mapped reads comes already normalised by genome length. This is a count not a metric which uses read length. So then it would just be `reads_per_base` * 10^9 / `total_reads_mapped_to_all_genomes` right?

**Comment by wwood** [comment]
Hi, I just pushed an rpkm calculator to the master branch, so can just run `-m rpkm` to get the RPKM for contigs or genomes.

**Comment by jerceyli** [comment]
> Hi, I just pushed an rpkm calculator to the master branch, so can just run `-m rpkm` to get the RPKM for contigs or genomes.

Sorry for the late reply. It is very kind of you, Thank you!!
