### ISSUE TITLE
How to output bam file after trimmed_mean function?

### ISSUE THREAD

**Issue by Harper19** [wwood/CoverM#206]
Hello, I would like to check the coverage difference before and after trimmed_mean. Currently I am thinking to create depth table and plots using old vs new bamfiles to check. 

However, cannot output the trimmed bam file. Is there anyway to do it? Or is there any suggestion to do it based on coverm?

Thanks for your attention and time!

Best,
Harper

**Comment by wwood** [comment]
Hi,

I'm not sure this is possible because it isn't quite specified properly.

Trimmed mean is calculated by getting the coverage of each column, and then removing coverage numbers at the 10 and 90% values. So there might be multiple positions with the same coverage, where some are inside 10-90% and some are outside.

If you are interested, I'd suggest using the coverage_histogram output, manually calculating the 10th and 90th percentiles, and then interrogating your BAM file based on that.

HTH, ben

**Comment by Harper19** [comment]
Thank you so much. I will try to do it.
Best,
Harper
