### ISSUE TITLE
Running multiple methods with one command

### ISSUE THREAD

**Issue by elizabethmcd** [wwood/CoverM#21]
Hi, thanks for the great tool. I couldn't tell from the documentation if you can run multiple methods in the same command, such as if I want to have the output method be both relative_abundance and coverage_histogram without having to run them as separate jobs. I understand I could probably use the coverage_histogram output and manually calculate the relative abundance, but would be nice to have those output results from one run. Apologies if this was already explained in the documentation and I missed it. 
Thanks.

**Comment by wwood** [comment]
Hi,

Thanks for your interest. In most cases, you can just put the methods you want like this
```
coverm -m relative_abundance mean variance ...
```
Unfortunately though the coverage histogram method is an exception - it must be used alone, because it doesn't fit well with the output format of other methods. If you are worried about mapping time you can run it with `--bam-file-cache-directory` the first time, and then `-b` then next.

Hope that clears things up.
ben

**Comment by elizabethmcd** [comment]
That works, thanks!
