### ISSUE TITLE
Warn user if it inputs an unsorted BAM file

### ISSUE THREAD

**Issue by apcamargo** [wwood/CoverM#26]
CoverM gives wrong results if the BAM files are not sorted and it doesn't warn the user that the input should be sorted.

`jgi_summarize_bam_contig_depths` raises the following error message if the input is not sorted:

```
ERROR: the bam file 'test_sequences.bam' is not sorted!
Please execute 'samtools sort' on unsorted input bam files and try again!
```

**Comment by wwood** [comment]
Thanks. I've known about this for a while but was putting it off because I didn't want to struggle with what a sort by reference name means specifically in the nitty gritty of alpha-numerics. But then as soon as I started implementing it I realised all that is required is comparing tid integers, so much simpler.

I went for error rather than warn because it is death, really.

**Comment by apcamargo** [comment]
Thanks!

Just out of curiosity, is there any advantage of checking if target ids are numerically order compared to just checking the header (`SO:coordinate`)?

**Comment by wwood** [comment]
I guess just because it doesn't actually have to be sorted properly - all that is actually required is that the reads mapping to a reference are grouped together, and when using a separator the references belonging to a genome must also be grouped. But apart from that it doesn't need to be sorted - actually samtools sort is overkill, it's just easier to explain to users.
