### ISSUE TITLE
--bam-files incompatible with --min-read-*-pair

### ISSUE THREAD

**Issue by simone-pignotti** [wwood/CoverM#65]
Hi,

Thanks for maintaining this great tool!

I encountered the following error:

```
$ coverm contig -b test.bam -o test.tsv -m mean -t 4 --no-zeros --min-read-percent-identity-pair 75 --min-read-aligned-percent-pair 60 --exclude-supplementary --min-covered-fraction 1e-10

error: The following required arguments were not provided:
    --coupled <coupled>...
    --interleaved <interleaved>...
    --proper-pairs-only
    -1 <read1>...
    -2 <read2>...
    --reference <reference>...
    --single <single>...

USAGE:
    coverm contig --bam-files <bam-files>... --contig-end-exclusion <contig-end-exclusion> --coupled <coupled>... --exclude-supplementary --interleaved <interleaved>... --mapper <mapper> --methods <methods>... --min-covered-fraction <min-covered-fraction> --min-read-aligned-percent-pair <min-read-aligned-percent-pair> --min-read-percent-identity-pair <min-read-percent-identity-pair> --no-zeros --output-file <output-file> --output-format <output-format> --proper-pairs-only -1 <read1>... -2 <read2>... --reference <reference>... --single <single>... --threads <threads> --trim-max <trim-max> --trim-min <trim-min>

For more information try --help
```

Removing the options `--min-read-percent-identity-pair` and `--min-read-aligned-percent-pair` worked. It would be ideal to have a clearer error message (can be as simple as `--min-read-percent-identity-pair` is not compatible with `--bam-files`), as it's the case when using e.g. `-m metabat` with `--min-covered-fraction`:
```
$ coverm contig -b raw_EB003-DS014-NT.bam -o raw_EB003-DS014-NT.coverm -m metabat -t 4 --no-zeros --exclude-supplementary --min-covered-fraction 1e-10

[2021-04-27T14:06:50Z INFO  coverm] CoverM version 0.6.1
[2021-04-27T14:06:50Z INFO  coverm] Setting single read percent identity threshold at 0.97 for MetaBAT adjusted coverage, and not filtering out supplementary, secondary and improper pair alignments
[2021-04-27T14:06:50Z INFO  coverm] Writing output to file: raw_EB003-DS014-NT.coverm
[2021-04-27T14:06:50Z INFO  coverm] Using min-covered-fraction 0.00000001%
[2021-04-27T14:06:50Z ERROR coverm] The 'length' coverage estimator cannot be used when --min-covered-fraction is > 0 as it does not calculate the covered fraction. You may wish to set the --min-covered-fraction to 0 and/or run this estimator separately.
```

Thanks

**Comment by ZongzhiWu** [comment]
Hi simone, how and why do you set --min-covered-fraction 1e-10? If I want to screen contigs with ≥70% of their length
covered by the reads. What --min-covered-fraction should I set?

**Comment by simone-pignotti** [comment]
Hi @ZongzhiWu, according to the [documentation](https://wwood.github.io/CoverM/coverm-contig.html):
> Genomes with less coverage than this reported as having zero coverage. [default: 10]

In my case I wanted to report even contigs with a few reads mapped to them. I am not sure whether you need to use 70 or 0.7. I also have a little doubt about the language used (covered fraction for me would be the number of based covered by at least one read, but "Genomes with less coverage than this" has a completely different meaning, and I am not sure which one is correct).
I think your best bet is to use `--min-covered-fraction 0 -m covered_fraction` (together with other methods, separated by spaces, if needed) and use awk or similar to filter the output.

**Comment by ZongzhiWu** [comment]
I've got it. Thanks a lot. : )

**Comment by wwood** [comment]
Hi @simone-pignotti 

* I agree the error message is somewhat cryptic. Unfortunately that error message is auto-generated and not so straightforward to fix. What it should say is, `using --min-read-percent-identity-pair requires --proper-pairs-only to also be set.`
* For `-m metabat --min-covered-fraction 1e-10`, you could instead run `min_percent_identity_single = 0.97001` and `-m mean variance covered_fraction length` and then filter on the covered_fraction. But in effect you could just run with `-m metabat --min-covered-fraction 0` and filter out anything with mean coverage > 0, right? Unfortunately min-covered-fraction is given to each method's calculator, so found separately, and the length method doesn't know about coverage, as the error message says.
* For --min-covered-fraction, 70 or 0.7 do the same thing, internally they are both used as 70%. The logging message says this when --min-covered-fraction is specified.

I'm leaving this issue open because the error messages aren't good enough, as you suggest. Will fix.

**Comment by wwood** [comment]
Hi, I think the error message in the main branch is better now, so closing.
