### ISSUE TITLE
Supplementary mappings in BAM file

### ISSUE THREAD

**Issue by dparks1134** [wwood/CoverM#93]
Hi Ben,

I'm running `coverm contig` with the `--exclude-supplementary` flag. However, if I run `samtools flagstat` on the resulting BAM file it reports supplementary alignments. 

Is this the expected behaviour? Does  `--exclude-supplementary` mean the supplementary alignments aren't used to calculate coverage, but that they will still be present in the BAM file.

Thanks,
Donovan

**Comment by wwood** [comment]
Hi Donovan,

Yes good point. I believe this is already fixed in main, specifically in 6180639549a - does compiling the main branch fix it for you?

Given the age of that commit it is probably time for a new release. I had hoped to get to your other suggestions around flag filtering first, but might be time to call it.
ben
