### ISSUE TITLE
Some questions about coverage calculation

### ISSUE THREAD

**Issue by MengzhiJ** [wwood/CoverM#95]
Hi, 
I want to calculate coverage for some common contigs in two metagenomic datasets to compare. The number of reads in the two metagenomes is same. But the length of reads in one metagenome is 150 bp, and another is 250 bp. Can I use the trimmed_mean method to calculate the coverage directly for comparison? Do I need to consider the length of the reads? Thank you!

**Comment by wwood** [comment]
Hi,

I would say that the length of the reads is important to consider, and I don't think `trimmed_mean` will get you there, because that is calculated over the coverage of each base, which will be more in the 250bp vs 150bp read set all other things being equal.

You could try using something that counts per-read e.g. `count`, `reads_per_base`, `rpkm` or `tpm`. Another alternative that might avoid issues that arise from the 250bp read having a higher chance to map (since it is easier to map a long read than a short one), is to truncate the 250bp reads to 150bp, and then choose any method including `trimmed_mean`.

Of course, there may be other reasons that make the comparison uncontrolled, I'm not sure. Good luck.
Thanks, ben

**Comment by MengzhiJ** [comment]
Thank you for your reply! I think I have a clear idea on this issue. I will choose RPKM or RPKG to caculate the coverage of contigs to compare. Thank you again for the excellent pipeline you have developed!
