### ISSUE TITLE
Which depth mectric would be best to use when reintroducing sample divisions to a metagenomic assembly?

### ISSUE THREAD

**Issue by Lamm-a** [wwood/CoverM#97]
Due to poor coverage we have co assembled within individuals (multiple samples per individual) across time points. We then want to look at the CAZYme and nitrogen fixing profiles across each sample and then for example look at GH family abundance per sample. Thus we need to recover our sample divisions. 

Using CoverM I can recover the `coverage fraction` and am filtering to not include anything below 25% coverage. However when it comes to depth I am unsure which metric to use. Would you implementation of the `metabat ` be a suitable depth metric here?

I think I need a depth metric that is scaled by  both contig length and total reads in a sample?

Do you have any insights into this?

Many thanks

**Comment by wwood** [comment]
Hi,

Do you mean genome-wise abundances? I would think that the default percent_abundance would be the most straightforward - this takes into account read library size and contig/genome length. 

I'm a little confused because you mention using metabat depth, but that is only available for contig mode.
